[package]
name = "fmtsrt"
version = "1.2.5"
authors = ["German David <germanmarinrolong@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.10", features = ["derive"] }
